Document: glasscoder
Title: Debian glasscoder Manual
Author: <insert document author here>
Abstract: This manual describes what glasscoder is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/glasscoder/glasscoder.sgml.gz

Format: postscript
Files: /usr/share/doc/glasscoder/glasscoder.ps.gz

Format: text
Files: /usr/share/doc/glasscoder/glasscoder.text.gz

Format: HTML
Index: /usr/share/doc/glasscoder/html/index.html
Files: /usr/share/doc/glasscoder/html/*.html
